/** @deprecated Import from `@/ui` — platform is not the visual owner. */
export {
  AgentCard,
  Breadcrumbs,
  CatalogGrid,
  CatalogToolbar,
  Container,
  type Crumb,
  CTA,
  DecisionSidebar,
  DeveloperCard,
  DevelopmentCard,
  EmptyState,
  ErrorState,
  FilterBar,
  Filters,
  Footer,
  Gallery,
  Header,
  ImageFrame,
  LeadForm,
  MobileNavigation,
  type NavGroup,
  type NavItem,
  PageBlock,
  PageShell,
  StarterPageShell,
  type StarterPageShellProps,
  Pagination,
  PriceDisplay,
  PropertyCard,
  Section,
  SectionHeader,
} from "@/ui";
